package io.home.pi.service;

import io.home.pi.persistence.model.User;
import io.home.pi.web.dto.UserDTO;
import io.home.pi.web.exception.UserAlreadyExistException;

/**
 * PROJECT   : pi
 * PACKAGE   : io.home.pi.service
 * USER      : sean
 * DATE      : 30-June-2018
 * TIME      : 13:58
 */
public interface UserRegService {
    User registerNewUserAccount(UserDTO userAccount) throws UserAlreadyExistException;

    /**
     * Sets the account-state to Disabled & saves the new User-Account.
     *
     * @param user  {@link User} to be saved.
     * @param token {@link String} token generated by the system.
     * @return Saved {@link User} object.
     */
    User createVerificationTokenForUser(final User user, final String token);

    String validateVerificationToken(String token);


}
